# ====== Stage 1: Builder ======
ARG BASE_IMAGE="gayrat/comfyui-base-cuda-12-4:v2.0"
FROM ${BASE_IMAGE} AS builder

WORKDIR /usr/local/bin
COPY ./bash-scripts/build/*.sh ./
#COPY *.sh ./
RUN chmod +x ./*.sh

WORKDIR /workspace
ARG COMFYUI_VERSION="latest"
ARG CUDA_VER="12.4"

ARG COLOR_GREEN='\033[32m'
ARG COLOR_RED='\033[31m'
ARG COLOR_YELLOW='\033[33m'
ARG COLOR_BOLD_GREEN='\033[1;32m'
ARG COLOR_RESET='\033[0m'

#RUN --mount=type=cache,target=/root/repo-cache \
#    --mount=type=cache,target=/root/pip-cache \
#    --mount=type=cache,target=/root/pip-cache-uv \
#    rm -rf /root/repo-cache/* && \
#    rm -rf /root/pip-cache/* && \
#    rm -rf /root/pip-cache-uv/*
#RUN exit 1

#RUN --mount=type=cache,target=/root/repo-cache \
#    rm -rf /root/repo-cache/*
#RUN exit 1



# Очистка директории и клонирование ComfyUI
RUN --mount=type=cache,target=/root/repo-cache \
    rm -rf /workspace/* && \
    git-clone-checkout.sh "https://github.com/comfyanonymous/ComfyUI" "$COMFYUI_VERSION" "/root/repo-cache"

WORKDIR /workspace/ComfyUI
COPY python-prg/remove-frontend-from-requirements.py .
RUN python3 remove-frontend-from-requirements.py

ARG COMFYUI_FRONTEND_VERSION

RUN --mount=type=cache,target=/root/pip-cache \
    python3 -m pip install --cache-dir=/root/pip-cache -r requirements.txt \
    python3 -m pip install --cache-dir=/root/pip-cache comfyui-frontend-package=="$COMFYUI_FRONTEND_VERSION" \
    && rm -rf /root/.cache/pip


COPY nodes.txt  ./

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_repos-install-req-hash.sh nodes.txt true \
    && rm -rf /root/.cache/pip

ARG REQ_MODIFY="base-CUDA-12.4"
COPY requirements-modify ./requirements-modify

ARG PYTORCH_WHEEL="https://download.pytorch.org/whl/cu124"

COPY ./python-prg/*.py ./gayrat_py/

# Устанавливаем UV_CACHE_DIR, чтобы uv использовал именно эту директорию для всего своего кеша
ENV UV_CACHE_DIR=/root/pip-cache-uv
ENV PIP_CACHE_DIR=/root/pip-cache-uv2
ENV UV_NO_CACHE=0
ENV UV_LINK_MODE=copy

RUN --mount=type=cache,target=/root/pip-cache \
  python3 -m pip install --cache-dir=/root/pip-cache opencv-python mediapipe scipy ultralytics onnxruntime-gpu transformers scikit-image accelerate

#в файле
#/workspace/ComfyUI/custom_nodes/ComfyUI-Manager/glob/cnr_utils.py #есть фрагмент кода
#            if page % 5 == 0:
#                print(f"FETCH ComfyRegistry Data: {page}/{sub_json_obj['totalPages']}")
#надо найти и удалить его

RUN sed -i '/if page % 5 == 0:/,+1d' /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/glob/cnr_utils.py

RUN python3 /workspace/ComfyUI/gayrat_py/remove_lines.py


#>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=
# ====== Stage 2: Final image ======
#>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=>=
RUN echo -e "\n\n${COLOR_GREEN}===== Вторая стадия сборки ========${COLOR_RESET}\n"
FROM ${BASE_IMAGE}

ARG PY_VER=3.11

# Копируем установленные системные Python-пакеты
RUN echo -e "Копируем установленные системные Python-пакеты"
#COPY --from=builder /usr/local/lib/python3.11/dist-packages /usr/local/lib/python3.11/dist-packages
COPY --from=builder "/usr/local/lib/python$PY_VER/dist-packages" "/usr/local/lib/python$PY_VER/dist-packages"

# Копируем рабочую директорию
RUN echo -e "Копируем рабочую директорию"
COPY --from=builder /workspace /workspace

ARG MODELS

ENV DOWNLOADS_DIR=/usr/local/bin

WORKDIR /usr/local/bin
COPY ./bash-scripts/build/*.sh $DOWNLOADS_DIR/
COPY ./bash-scripts/*.sh $DOWNLOADS_DIR/
COPY *.sh $DOWNLOADS_DIR/
RUN chmod +x $DOWNLOADS_DIR/*.sh

WORKDIR /workspace/ComfyUI
COPY ./custom-nodes/*.txt ./

# Copy the pre-built Apex wheel from your local host into the image
WORKDIR /workspace/wheels
COPY ./assets-docker/wheels/ ./

#COPY ./assets-docker/apex_wheel/apex-*.whl .
#COPY ./assets-docker/sageattention_wheel/sageattention-*.whl .
## Install the Apex wheel and then delete the file to keep the image clean
#RUN python3 -m pip install apex-*.whl && rm apex-*.whl





RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/gayratv/ComfyUI_Gayrat@10957f8dd56cc335c19be03b7f5eb79e5c21b647" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/chrisgoringe/cg-use-everywhere@a834f09f3889264f192711971ca624128650a250" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/rgthree/rgthree-comfy@944d5353a1b0a668f40844018c3dc956b95a67d7" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/pythongosssss/ComfyUI-Custom-Scripts@aac13aa7ce35b07d43633c3bbe654a38c00d74f5" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/1038lab/ComfyUI-RMBG@72bc6a5f8deca40f10d788503266b80c363374ab" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/city96/ComfyUI-GGUF@b3ec875a68d94b758914fd48d30571d953bb7a54" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/kijai/ComfyUI-KJNodes@a6b867b63a29ca48ddb15c589e17a9f2d8530d57" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/Jonseed/ComfyUI-Detail-Daemon@f391accbda2d309cdcbec65cb9fcc80a41197b20" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/Steudio/ComfyUI_Steudio@93fce9a5a7acf190f9bf44f4063ac508368c8ffe" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/WASasquatch/was-node-suite-comfyui@ea935d1044ae5a26efa54ebeb18fe9020af49a45" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/chflame163/ComfyUI_LayerStyle@3bfe8e435d167b4a5bf08716729f89802dbbaa6f" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/1038lab/ComfyUI-Pollinations@78d8ee093b3081c48815cf8df6486e3417de873b" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/kijai/ComfyUI-WanVideoWrapper@998a69cc0acbec503001b8b0ce0a5d5404420e1e" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/Fannovel16/comfyui_controlnet_aux@59b027e088c1c8facf7258f6e392d16d204b4d27" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/ltdrdata/ComfyUI-Impact-Pack@48a814315f500a6f3e87ac4c8446305f8b2ef8f6" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/kijai/ComfyUI-Florence2@de485b65b3e1b9b887ab494afa236dff4bef9a7e" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite@330bce6c3c0d47ebdedcc0348d9ab355707b7523" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/kijai/ComfyUI-segment-anything-2@c59676b008a76237002926f684d0ca3a9b29ac54" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes@d78b780ae43fcf8c6b7c6505e6ffb4584281ceca" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/cubiq/ComfyUI_essentials@9d9f4bedfc9f0321c19faf71855e228c93bd0dc9" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/un-seen/comfyui-tensorops@d34488e3079ecd10db2fe867c3a7af568115faed" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/yolain/ComfyUI-Easy-Use@717092a3ceb51c474b5b3f77fc188979f0db9d67" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/john-mnz/ComfyUI-Inspyrenet-Rembg@87ac452ef1182e8f35f59b04010158d74dcefd06" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/melMass/comfy_mtb@5c0e020c7303d3bf093d19f3a2064e5634531ff1" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/chflame163/ComfyUI_LayerStyle_Advance@b5d2c94637a629b6294d84e45e636010ca0280a3" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/kijai/ComfyUI-DepthAnythingV2@d505cbca99803fc63327b8305618a23e59a18b42" true \
    && rm -rf /root/.cache/pip

RUN --mount=type=cache,target=/root/repo-cache \
    --mount=type=cache,target=/root/pip-cache \
    PIP_CACHE_DIR=/root/pip-cache \
    process_one_repo_install_req_hash.sh "https://github.com/ltdrdata/ComfyUI-Inspire-Pack@04223778ea4fad60a4ceb6798f063ec6cdc0e1e0" true \
    && rm -rf /root/.cache/pip


ARG NODES


WORKDIR /workspace/ComfyUI/input
COPY input  ./



RUN echo 'alias python=/usr/local/bin/python3.11' >> /root/.bashrc \
    source /root/.bashrc

ARG DOWNLAD_MODELS
WORKDIR /workspace/templates/models
#RUN python3 /workspace/ComfyUI/gayrat_py/remove-models-dirs.py ${DOWNLAD_MODELS}
#RUN python3 /workspace/ComfyUI/gayrat_py/remove-models-dirs.py ${DOWNLAD_MODELS} --dry-run


WORKDIR /workspace/ComfyUI

# Создайте файл конфигурации
RUN echo '{"skip_update_check": true}' > /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/.skip_update_check

RUN echo "cd /workspace/aria2/templates" >> /root/.bashrc \
  && echo "set -g mouse on" >> /root/.tmux.conf


WORKDIR /workspace
RUN echo -e "\n========= POST_INSTALL ===============\n"

ARG POST_INSTALL

COPY post-install/ ./post-install

COPY requirements-modify/ ./requirements-modify

# ========================== блок коррекции установленных пакетов
RUN --mount=type=cache,target=/root/pip-cache \
  python3 -m pip uninstall -y onnxruntime onnxruntime-gpu xformers \
  && python3 -m pip install --cache-dir=/root/pip-cache onnxruntime-gpu hf_transfer

RUN --mount=type=cache,target=/root/pip-cache \
  python3 -m pip install  --cache-dir=/root/pip-cache xformers sageattention
# ==========================



WORKDIR /workspace
RUN --mount=type=cache,target=/root/pip-cache \
    if [ -n "$POST_INSTALL" ]; then \
        chmod +x "./post-install/$POST_INSTALL" && \
        echo -e "$COLOR_YELLOW\n\n========= Running $POST_INSTALL ==========$COLOR_RESET"; \
        ./post-install/"$POST_INSTALL"; \
    else \
        echo "Skipping post-install script"; \
    fi

WORKDIR /workspace/ComfyUI
COPY input/${MODELS} ./input/


WORKDIR /workspace/ComfyUI/models/embeddings
COPY assets-docker/embeddings/ .


WORKDIR /workspace/WAS_node/
COPY assets-docker/WAS_node/nsp_pantry.json .
RUN echo 'export WAS_CONFIG_DIR=/workspace/WAS_node' >> /root/.bashrc



RUN echo -e "\\033[31m Копирование template \\033[0m"

# Copy aria2 directory near the end and keep only selected model subfolders
ARG ARIA2_MODEL_DIRS=""
WORKDIR /workspace/aria2
COPY aria2 .
RUN if [ -n "$ARIA2_MODEL_DIRS" ]; then \
        for d in $(ls templates/models); do \
            echo "Checking $d"; \
            if ! echo " $ARIA2_MODEL_DIRS " | grep -q " $d "; then \
                rm -rf "templates/models/$d"; \
            fi; \
        done; \
    fi && \
    chmod +x *.sh && chmod +x ./templates/*.sh && rm -f ./templates/.env

ARG WORKFLOW_TO_COPY
WORKDIR /workspace/ComfyUI
COPY workflows/$WORKFLOW_TO_COPY user/default/workflows/$WORKFLOW_TO_COPY

WORKDIR /workspace/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/prompts
COPY workflows/$WORKFLOW_TO_COPY/prompts $WORKFLOW_TO_COPY/


ARG ARG_COPY_CSV=false

WORKDIR /workspace/ComfyUI/custom_nodes/ComfyUI-CSV-Loader/CSV/

COPY assets-docker/CSV ./

RUN if [ "$ARG_COPY_CSV" = "false"  ]; then \
      rm -rf /workspace/ComfyUI/custom_nodes/ComfyUI-CSV-Loader; \
    fi


WORKDIR /workspace/ComfyUI
COPY assets-docker/styles.csv ./
RUN if [ "$ARG_COPY_CSV" = "false" ]; then \
      rm -f styles.csv; \
    fi



WORKDIR /workspace/ComfyUI/user/default/
COPY ./user/default/comfy.settings.json .

WORKDIR /workspace/ComfyUI

CMD ["bash"]
